import { pathToFileURL } from 'node:url';
import path from 'node:path';
import { readFile, writeFile } from 'node:fs/promises';

export const RUNTIME_ALLOWED = new Set([
  'MIT',
  'BSD-2-Clause',
  'BSD-3-Clause',
  'Apache-2.0',
  'ISC',
  '0BSD',
  'Unlicense',
]);
export const DEV_ALLOWED = new Set([...RUNTIME_ALLOWED, 'MPL-2.0']);

/** Normalise npm's several licence shapes into one string. */
export function normalizeLicense(raw) {
  if (!raw) return 'UNKNOWN';
  if (typeof raw === 'string') return raw.trim() || 'UNKNOWN';
  if (typeof raw === 'object' && typeof raw.type === 'string') return raw.type.trim() || 'UNKNOWN';
  return 'UNKNOWN';
}

/**
 * Judge each package against its scope's allow-list.
 * SPDX expressions (anything containing OR/AND/WITH or parentheses) are rejected
 * outright: an ambiguous grant is not something we ship without a human decision.
 */
export function classify(packages) {
  const violations = [];
  for (const pkg of packages) {
    const allowed = pkg.scope === 'runtime' ? RUNTIME_ALLOWED : DEV_ALLOWED;
    const isExpression = /[()]|\s(OR|AND|WITH)\s/.test(pkg.license);

    if (isExpression) {
      violations.push({
        ...pkg,
        reason: `${pkg.license} is a compound SPDX expression; resolve it to a single licence before shipping (${pkg.scope})`,
      });
    } else if (!allowed.has(pkg.license)) {
      violations.push({ ...pkg, reason: `${pkg.license} is not permitted for ${pkg.scope} dependencies` });
    }
  }
  return { ok: violations.length === 0, violations };
}

async function readManifest(root, name) {
  try {
    return JSON.parse(await readFile(path.join(root, 'node_modules', name, 'package.json'), 'utf8'));
  } catch {
    return null;
  }
}

/**
 * Read licence metadata from node_modules.
 *
 * Runtime dependencies are walked TRANSITIVELY, because everything reachable
 * from `dependencies` can end up in the shipped bundle. Dev dependencies are
 * audited at the top level only — they never reach dist/, so their transitive
 * tree is deliberately out of scope.
 */
export async function collectPackages(root = process.cwd()) {
  const pkg = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
  const seen = new Map();

  const record = (name, meta, scope) => {
    seen.set(name, {
      name,
      version: meta?.version ?? 'not-installed',
      license: meta ? normalizeLicense(meta.license ?? meta.licenses?.[0]?.type ?? meta.licenses?.[0]) : 'UNKNOWN',
      scope,
    });
  };

  // Runtime: breadth-first over the whole reachable graph.
  const queue = Object.keys(pkg.dependencies ?? {});
  while (queue.length > 0) {
    const name = queue.shift();
    if (seen.has(name)) continue;
    const meta = await readManifest(root, name);
    record(name, meta, 'runtime');
    for (const child of Object.keys(meta?.dependencies ?? {})) {
      if (!seen.has(child)) queue.push(child);
    }
  }

  // Dev: declared packages only. A name already recorded as runtime stays runtime.
  for (const name of Object.keys(pkg.devDependencies ?? {})) {
    if (seen.has(name)) continue;
    record(name, await readManifest(root, name), 'dev');
  }

  return [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));
}

/** Build the THIRD-PARTY-NOTICES.md body. */
export function renderNotices(packages) {
  const section = (title, scope) => {
    const rows = packages
      .filter((p) => p.scope === scope)
      .map((p) => `| ${p.name} | ${p.version} | ${p.license} |`)
      .join('\n');
    return `## ${title}\n\n| Package | Version | Licence |\n|---|---|---|\n${rows}\n`;
  };

  return [
    '# Third-party notices',
    '',
    'theme1 is MIT licensed. It builds on the following packages, each under its own licence.',
    'This file is generated by `scripts/license-audit.mjs` — do not edit by hand.',
    '',
    section('Runtime dependencies', 'runtime'),
    '',
    section('Development dependencies', 'dev'),
  ].join('\n');
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const root = process.cwd();
  const packages = await collectPackages(root);
  const { ok, violations } = classify(packages);

  await writeFile(path.join(root, 'THIRD-PARTY-NOTICES.md'), renderNotices(packages), 'utf8');

  if (!ok) {
    console.error('Licence audit FAILED:\n');
    for (const v of violations) console.error(`  ${v.name}@${v.version} — ${v.reason}`);
    process.exit(1);
  }
  console.log(`Licence audit passed: ${packages.length} packages, all permitted.`);
}
